server:
  port: 8081
spring:
  cloud:
   config:
    server:
     git:
      default-label: service-config
      uri: https://github.com/FedeVB/microservicios.git
      search-paths: config-data
  application:
    name: config-service    